name: CarbonAI
targets:
  CarbonAI:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: [CarbonAI]
    info:
      path: ./Info.plist
      version: 0.3.50
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
      - carthage: AnyCodable