//
// AccountsOrderByNullable.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum AccountsOrderByNullable: String, Codable, CaseIterable {
    case createdAt = "created_at"
    case updatedAt = "updated_at"
    case numberOfEmployees = "number_of_employees"
    case name = "name"
    case lastActivityAt = "last_activity_at"
}
