//
// Address.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Address: Codable, JSONEncodable, Hashable {

    public var street1: String?
    public var street2: String?
    public var city: String?
    public var state: String?
    public var postalCode: String?
    public var country: String?
    public var addressType: String?

    public init(street1: String?, street2: String?, city: String?, state: String?, postalCode: String?, country: String?, addressType: String?) {
        self.street1 = street1
        self.street2 = street2
        self.city = city
        self.state = state
        self.postalCode = postalCode
        self.country = country
        self.addressType = addressType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case street1 = "street_1"
        case street2 = "street_2"
        case city
        case state
        case postalCode = "postal_code"
        case country
        case addressType = "address_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encode(street1, forKey: .street1)
        try codingContainer.encode(street2, forKey: .street2)
        try codingContainer.encode(city, forKey: .city)
        try codingContainer.encode(state, forKey: .state)
        try codingContainer.encode(postalCode, forKey: .postalCode)
        try codingContainer.encode(country, forKey: .country)
        try codingContainer.encode(addressType, forKey: .addressType)
    }
}

