//
// AzureBlobStorageTypes.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum AzureBlobStorageTypes: String, Codable, CaseIterable {
    case container = "Container"
}
