//
// AzureBlobGetFileInput.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AzureBlobGetFileInput: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var container: String?

    public init(id: String? = nil, container: String? = nil) {
        self.id = id
        self.container = container
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case container
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(container, forKey: .container)
    }
}

