//
// BodyCreateUploadFileUploadfilePost.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BodyCreateUploadFileUploadfilePost: Codable, JSONEncodable, Hashable {

    public var file: URL

    public init(file: URL) {
        self.file = file
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case file
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encode(file, forKey: .file)
    }
}

