//
// CommentsOrderBy.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum CommentsOrderBy: String, Codable, CaseIterable {
    case created = "created"
    case updated = "updated"
}
