//
// ConfigurationKeys.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ConfigurationKeys: String, Codable, CaseIterable {
    case sparseVectors = "sparse_vectors"
}
