//
// ConfluenceFileTypes.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ConfluenceFileTypes: String, Codable, CaseIterable {
    case space = "SPACE"
    case page = "PAGE"
}
