//
// DataSourceExtendedInput.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum DataSourceExtendedInput: String, Codable, CaseIterable {
    case all = "ALL"
}
