//
// DeleteUsersInput.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeleteUsersInput: Codable, JSONEncodable, Hashable {

    public var customerIds: [String]

    public init(customerIds: [String]) {
        self.customerIds = customerIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customerIds = "customer_ids"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encode(customerIds, forKey: .customerIds)
    }
}

