//
// EmbeddingProperties.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmbeddingProperties: Codable, JSONEncodable, Hashable {

    public var chunkSize: Int?
    public var chunkOverlap: Int?

    public init(chunkSize: Int?, chunkOverlap: Int?) {
        self.chunkSize = chunkSize
        self.chunkOverlap = chunkOverlap
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case chunkSize = "chunk_size"
        case chunkOverlap = "chunk_overlap"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encode(chunkSize, forKey: .chunkSize)
        try codingContainer.encode(chunkOverlap, forKey: .chunkOverlap)
    }
}

