//
// ExternalDataSourceType.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ExternalDataSourceType: String, Codable, CaseIterable {
    case box = "BOX"
    case confluence = "CONFLUENCE"
    case dropbox = "DROPBOX"
    case gmail = "GMAIL"
    case googleDrive = "GOOGLE_DRIVE"
    case googleCloudStorage = "GOOGLE_CLOUD_STORAGE"
    case intercom = "INTERCOM"
    case notion = "NOTION"
    case onedrive = "ONEDRIVE"
    case outlook = "OUTLOOK"
    case salesforce = "SALESFORCE"
    case sharepoint = "SHAREPOINT"
    case slack = "SLACK"
    case zendesk = "ZENDESK"
    case zotero = "ZOTERO"
}
