//
// ExternalSourceItemsOrderBy.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ExternalSourceItemsOrderBy: String, Codable, CaseIterable {
    case name = "name"
    case id = "id"
    case directoriesFirst = "directories_first"
}
