//
// FileStatus.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum FileStatus: String, Codable, CaseIterable {
    case added = "added"
    case removed = "removed"
    case modified = "modified"
    case renamed = "renamed"
    case copied = "copied"
    case changed = "changed"
    case unchanged = "unchanged"
}
