//
// FreskdeskAuthentication.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FreskdeskAuthentication: Codable, JSONEncodable, Hashable {

    public enum Source: String, Codable, CaseIterable {
        case freshdesk = "FRESHDESK"
    }
    public var source: Source
    public var domain: String
    public var apiKey: String

    public init(source: Source, domain: String, apiKey: String) {
        self.source = source
        self.domain = domain
        self.apiKey = apiKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case source
        case domain
        case apiKey = "api_key"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encode(source, forKey: .source)
        try codingContainer.encode(domain, forKey: .domain)
        try codingContainer.encode(apiKey, forKey: .apiKey)
    }
}

