//
// GitbookAuthetication.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GitbookAuthetication: Codable, JSONEncodable, Hashable {

    public enum Source: String, Codable, CaseIterable {
        case gitbook = "GITBOOK"
    }
    public var source: Source
    public var accessToken: String
    public var organizationName: String

    public init(source: Source, accessToken: String, organizationName: String) {
        self.source = source
        self.accessToken = accessToken
        self.organizationName = organizationName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case source
        case accessToken = "access_token"
        case organizationName = "organization_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encode(source, forKey: .source)
        try codingContainer.encode(accessToken, forKey: .accessToken)
        try codingContainer.encode(organizationName, forKey: .organizationName)
    }
}

