//
// GithubFetchReposRequest.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GithubFetchReposRequest: Codable, JSONEncodable, Hashable {

    public var repos: [String]
    public var dataSourceId: Int?

    public init(repos: [String], dataSourceId: Int? = nil) {
        self.repos = repos
        self.dataSourceId = dataSourceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case repos
        case dataSourceId = "data_source_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encode(repos, forKey: .repos)
        try codingContainer.encodeIfPresent(dataSourceId, forKey: .dataSourceId)
    }
}

