//
// HeadOrBase.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HeadOrBase: Codable, JSONEncodable, Hashable {

    public var label: String
    public var ref: String
    public var sha: String

    public init(label: String, ref: String, sha: String) {
        self.label = label
        self.ref = ref
        self.sha = sha
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case label
        case ref
        case sha
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encode(label, forKey: .label)
        try codingContainer.encode(ref, forKey: .ref)
        try codingContainer.encode(sha, forKey: .sha)
    }
}

