//
// IntercomFileTypes.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum IntercomFileTypes: String, Codable, CaseIterable {
    case article = "ARTICLE"
    case collection = "COLLECTION"
    case helpCenter = "HELP_CENTER"
    case ticket = "TICKET"
    case ticketAttachment = "TICKET_ATTACHMENT"
    case contact = "CONTACT"
    case admin = "ADMIN"
    case team = "TEAM"
    case conversation = "CONVERSATION"
}
