//
// IssuesResponse.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IssuesResponse: Codable, JSONEncodable, Hashable {

    public var data: [Issue]
    public var nextCursor: String?

    public init(data: [Issue], nextCursor: String?) {
        self.data = data
        self.nextCursor = nextCursor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case nextCursor = "next_cursor"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encode(data, forKey: .data)
        try codingContainer.encode(nextCursor, forKey: .nextCursor)
    }
}

