//
// ListUsersOrderByTypes.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ListUsersOrderByTypes: String, Codable, CaseIterable {
    case createdAt = "created_at"
    case updatedAt = "updated_at"
}
