//
// MoveToHotStorageQueryInput.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MoveToHotStorageQueryInput: Codable, JSONEncodable, Hashable {

    public var filters: OrganizationUserFilesToSyncFilters?

    public init(filters: OrganizationUserFilesToSyncFilters? = nil) {
        self.filters = filters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filters
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encodeIfPresent(filters, forKey: .filters)
    }
}

