//
// MultiModalEmbeddingGenerators.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum MultiModalEmbeddingGenerators: String, Codable, CaseIterable {
    case vertexMultimodal = "VERTEX_MULTIMODAL"
}
