//
// OpportunityStatus.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum OpportunityStatus: String, Codable, CaseIterable {
    case won = "WON"
    case _open = "OPEN"
}
