//
// OrderDirV2.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum OrderDirV2: String, Codable, CaseIterable {
    case asc = "asc"
    case desc = "desc"
}
