//
// PRStateInput.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PRStateInput: String, Codable, CaseIterable {
    case closed = "closed"
    case _open = "open"
    case all = "all"
}
