//
// PullRequestFilters.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PullRequestFilters: Codable, JSONEncodable, Hashable {

    public var state: PRStateInput?
    /** Filter pulls by base branch name */
    public var base: String?
    /** Filter pulls by head user or head organization and branch name in the format of user:ref-name or organization:ref-name */
    public var head: String?

    public init(state: PRStateInput? = nil, base: String? = nil, head: String? = nil) {
        self.state = state
        self.base = base
        self.head = head
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case state
        case base
        case head
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encodeIfPresent(state, forKey: .state)
        try codingContainer.encodeIfPresent(base, forKey: .base)
        try codingContainer.encodeIfPresent(head, forKey: .head)
    }
}

