//
// RemoveDataSourceTagsInput.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RemoveDataSourceTagsInput: Codable, JSONEncodable, Hashable {

    public var dataSourceId: Int
    public var tagsToRemove: [String]?
    public var removeAllTags: Bool? = false

    public init(dataSourceId: Int, tagsToRemove: [String]? = nil, removeAllTags: Bool? = false) {
        self.dataSourceId = dataSourceId
        self.tagsToRemove = tagsToRemove
        self.removeAllTags = removeAllTags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dataSourceId = "data_source_id"
        case tagsToRemove = "tags_to_remove"
        case removeAllTags = "remove_all_tags"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encode(dataSourceId, forKey: .dataSourceId)
        try codingContainer.encodeIfPresent(tagsToRemove, forKey: .tagsToRemove)
        try codingContainer.encodeIfPresent(removeAllTags, forKey: .removeAllTags)
    }
}

