//
// SentWebhookPayloadObjectAdditionalInformation.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum SentWebhookPayloadObjectAdditionalInformation: Codable, JSONEncodable, Hashable {
    case typeAnyCodable(AnyCodable)
    case typeNull(Null)
    case typeString(String)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeAnyCodable(let value):
            try container.encode(value)
        case .typeNull(let value):
            try container.encode(value)
        case .typeString(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(AnyCodable.self) {
            self = .typeAnyCodable(value)
        } else if let value = try? container.decode(Null.self) {
            self = .typeNull(value)
        } else if let value = try? container.decode(String.self) {
            self = .typeString(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of SentWebhookPayloadObjectAdditionalInformation"))
        }
    }
}

