//
// SharedSourceItemTypes.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum SharedSourceItemTypes: String, Codable, CaseIterable {
    case file = "FILE"
    case folder = "FOLDER"
}
