//
// SingleChunksAndEmbeddingsUploadInput.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SingleChunksAndEmbeddingsUploadInput: Codable, JSONEncodable, Hashable {

    public var fileId: Int
    public var chunkSize: Int?
    public var chunkOverlap: Int?
    public var chunksAndEmbeddings: [ChunksAndEmbeddings]

    public init(fileId: Int, chunkSize: Int? = nil, chunkOverlap: Int? = nil, chunksAndEmbeddings: [ChunksAndEmbeddings]) {
        self.fileId = fileId
        self.chunkSize = chunkSize
        self.chunkOverlap = chunkOverlap
        self.chunksAndEmbeddings = chunksAndEmbeddings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fileId = "file_id"
        case chunkSize = "chunk_size"
        case chunkOverlap = "chunk_overlap"
        case chunksAndEmbeddings = "chunks_and_embeddings"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encode(fileId, forKey: .fileId)
        try codingContainer.encodeIfPresent(chunkSize, forKey: .chunkSize)
        try codingContainer.encodeIfPresent(chunkOverlap, forKey: .chunkOverlap)
        try codingContainer.encode(chunksAndEmbeddings, forKey: .chunksAndEmbeddings)
    }
}

