//
// SlackFilters.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SlackFilters: Codable, JSONEncodable, Hashable {

    /** Conversation ID from slack, can be obtained from Carbon with slack conversations endpoint */
    public var conversationId: String
    /** Only messages after this date will be included in results. If not set, all messages          will be included. Should be entered in YYYY/mm/dd format */
    public var after: String?

    public init(conversationId: String, after: String? = nil) {
        self.conversationId = conversationId
        self.after = after
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case conversationId = "conversation_id"
        case after
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encode(conversationId, forKey: .conversationId)
        try codingContainer.encodeIfPresent(after, forKey: .after)
    }
}

