//
// Task.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Task: Codable, JSONEncodable, Hashable {

    public var description: String?
    public var id: String
    public var owner: PartialOwner
    public var subject: String?
    public var status: String?
    public var priority: String?
    public var account: PartialAccountNullable?
    public var contact: PartialContactNullable?
    public var createdAt: String
    public var updatedAt: String
    public var isDeleted: Bool
    public var remoteData: AnyCodable?

    public init(description: String?, id: String, owner: PartialOwner, subject: String?, status: String?, priority: String?, account: PartialAccountNullable?, contact: PartialContactNullable?, createdAt: String, updatedAt: String, isDeleted: Bool, remoteData: AnyCodable?) {
        self.description = description
        self.id = id
        self.owner = owner
        self.subject = subject
        self.status = status
        self.priority = priority
        self.account = account
        self.contact = contact
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.isDeleted = isDeleted
        self.remoteData = remoteData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case id
        case owner
        case subject
        case status
        case priority
        case account
        case contact
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case isDeleted = "is_deleted"
        case remoteData = "remote_data"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encode(description, forKey: .description)
        try codingContainer.encode(id, forKey: .id)
        try codingContainer.encode(owner, forKey: .owner)
        try codingContainer.encode(subject, forKey: .subject)
        try codingContainer.encode(status, forKey: .status)
        try codingContainer.encode(priority, forKey: .priority)
        try codingContainer.encode(account, forKey: .account)
        try codingContainer.encode(contact, forKey: .contact)
        try codingContainer.encode(createdAt, forKey: .createdAt)
        try codingContainer.encode(updatedAt, forKey: .updatedAt)
        try codingContainer.encode(isDeleted, forKey: .isDeleted)
        try codingContainer.encode(remoteData, forKey: .remoteData)
    }
}

