//
// TranscriptionServiceNullable.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum TranscriptionServiceNullable: String, Codable, CaseIterable {
    case assemblyai = "assemblyai"
    case deepgram = "deepgram"
}
