//
// Tree.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Tree: Codable, JSONEncodable, Hashable {

    public var sha: String
    public var url: String

    public init(sha: String, url: String) {
        self.sha = sha
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sha
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encode(sha, forKey: .sha)
        try codingContainer.encode(url, forKey: .url)
    }
}

