//
// UpdateOrganizationInput.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateOrganizationInput: Codable, JSONEncodable, Hashable {

    public var globalUserConfig: UserConfigurationNullable?

    public init(globalUserConfig: UserConfigurationNullable? = nil) {
        self.globalUserConfig = globalUserConfig
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case globalUserConfig = "global_user_config"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(globalUserConfig, forKey: .globalUserConfig)
    }
}

