//
// UserWebPagesRequest.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserWebPagesRequest: Codable, JSONEncodable, Hashable {

    public var filters: UserWebPagesFilters?
    public var pagination: Pagination?
    public var orderBy: UserWebPageOrderByTypes?
    public var orderDir: OrderDirV2?

    public init(filters: UserWebPagesFilters? = nil, pagination: Pagination? = nil, orderBy: UserWebPageOrderByTypes? = nil, orderDir: OrderDirV2? = nil) {
        self.filters = filters
        self.pagination = pagination
        self.orderBy = orderBy
        self.orderDir = orderDir
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filters
        case pagination
        case orderBy = "order_by"
        case orderDir = "order_dir"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encodeIfPresent(filters, forKey: .filters)
        try codingContainer.encodeIfPresent(pagination, forKey: .pagination)
        try codingContainer.encodeIfPresent(orderBy, forKey: .orderBy)
        try codingContainer.encodeIfPresent(orderDir, forKey: .orderDir)
    }
}

