//
// UserFile.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserFile: Codable, JSONEncodable, Hashable {

    public var tags: AnyCodable?
    public var id: Int
    public var source: DataSourceType
    public var organizationId: Int
    public var organizationSuppliedUserId: String
    public var organizationUserDataSourceId: Int?
    public var externalFileId: String
    public var externalUrl: String?
    public var syncStatus: ExternalFileSyncStatuses
    public var syncErrorMessage: String?
    public var lastSync: Date?
    public var fileStatistics: FileStatisticsNullable?
    public var fileMetadata: AnyCodable?
    public var embeddingProperties: [String: EmbeddingProperties]?
    public var chunkSize: Int?
    public var chunkOverlap: Int?
    public var chunkProperties: ChunkPropertiesNullable?
    public var ocrProperties: AnyCodable
    public var ocrJobStartedAt: Date?
    public var name: String?
    public var parentId: Int?
    public var enableAutoSync: Bool?
    public var presignedUrl: String?
    public var parsedTextUrl: String?
    public var additionalPresignedUrls: AnyCodable?
    public var skipEmbeddingGeneration: Bool
    public var sourceCreatedAt: Date?
    public var generateSparseVectors: Bool?
    public var requestId: String?
    public var uploadId: String?
    public var syncProperties: AnyCodable
    public var messagesMetadata: AnyCodable
    public var fileContentsDeleted: Bool = false
    public var supportsColdStorage: Bool
    public var hotStorageTimeToLive: Int?
    public var embeddingStorageStatus: EmbeddingStorageStatus
    public var createdAt: Date
    public var updatedAt: Date

    public init(tags: AnyCodable?, id: Int, source: DataSourceType, organizationId: Int, organizationSuppliedUserId: String, organizationUserDataSourceId: Int?, externalFileId: String, externalUrl: String?, syncStatus: ExternalFileSyncStatuses, syncErrorMessage: String?, lastSync: Date?, fileStatistics: FileStatisticsNullable?, fileMetadata: AnyCodable?, embeddingProperties: [String: EmbeddingProperties]?, chunkSize: Int?, chunkOverlap: Int?, chunkProperties: ChunkPropertiesNullable?, ocrProperties: AnyCodable, ocrJobStartedAt: Date?, name: String?, parentId: Int?, enableAutoSync: Bool?, presignedUrl: String?, parsedTextUrl: String?, additionalPresignedUrls: AnyCodable?, skipEmbeddingGeneration: Bool, sourceCreatedAt: Date?, generateSparseVectors: Bool?, requestId: String?, uploadId: String?, syncProperties: AnyCodable, messagesMetadata: AnyCodable, fileContentsDeleted: Bool = false, supportsColdStorage: Bool, hotStorageTimeToLive: Int?, embeddingStorageStatus: EmbeddingStorageStatus, createdAt: Date, updatedAt: Date) {
        self.tags = tags
        self.id = id
        self.source = source
        self.organizationId = organizationId
        self.organizationSuppliedUserId = organizationSuppliedUserId
        self.organizationUserDataSourceId = organizationUserDataSourceId
        self.externalFileId = externalFileId
        self.externalUrl = externalUrl
        self.syncStatus = syncStatus
        self.syncErrorMessage = syncErrorMessage
        self.lastSync = lastSync
        self.fileStatistics = fileStatistics
        self.fileMetadata = fileMetadata
        self.embeddingProperties = embeddingProperties
        self.chunkSize = chunkSize
        self.chunkOverlap = chunkOverlap
        self.chunkProperties = chunkProperties
        self.ocrProperties = ocrProperties
        self.ocrJobStartedAt = ocrJobStartedAt
        self.name = name
        self.parentId = parentId
        self.enableAutoSync = enableAutoSync
        self.presignedUrl = presignedUrl
        self.parsedTextUrl = parsedTextUrl
        self.additionalPresignedUrls = additionalPresignedUrls
        self.skipEmbeddingGeneration = skipEmbeddingGeneration
        self.sourceCreatedAt = sourceCreatedAt
        self.generateSparseVectors = generateSparseVectors
        self.requestId = requestId
        self.uploadId = uploadId
        self.syncProperties = syncProperties
        self.messagesMetadata = messagesMetadata
        self.fileContentsDeleted = fileContentsDeleted
        self.supportsColdStorage = supportsColdStorage
        self.hotStorageTimeToLive = hotStorageTimeToLive
        self.embeddingStorageStatus = embeddingStorageStatus
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tags
        case id
        case source
        case organizationId = "organization_id"
        case organizationSuppliedUserId = "organization_supplied_user_id"
        case organizationUserDataSourceId = "organization_user_data_source_id"
        case externalFileId = "external_file_id"
        case externalUrl = "external_url"
        case syncStatus = "sync_status"
        case syncErrorMessage = "sync_error_message"
        case lastSync = "last_sync"
        case fileStatistics = "file_statistics"
        case fileMetadata = "file_metadata"
        case embeddingProperties = "embedding_properties"
        case chunkSize = "chunk_size"
        case chunkOverlap = "chunk_overlap"
        case chunkProperties = "chunk_properties"
        case ocrProperties = "ocr_properties"
        case ocrJobStartedAt = "ocr_job_started_at"
        case name
        case parentId = "parent_id"
        case enableAutoSync = "enable_auto_sync"
        case presignedUrl = "presigned_url"
        case parsedTextUrl = "parsed_text_url"
        case additionalPresignedUrls = "additional_presigned_urls"
        case skipEmbeddingGeneration = "skip_embedding_generation"
        case sourceCreatedAt = "source_created_at"
        case generateSparseVectors = "generate_sparse_vectors"
        case requestId = "request_id"
        case uploadId = "upload_id"
        case syncProperties = "sync_properties"
        case messagesMetadata = "messages_metadata"
        case fileContentsDeleted = "file_contents_deleted"
        case supportsColdStorage = "supports_cold_storage"
        case hotStorageTimeToLive = "hot_storage_time_to_live"
        case embeddingStorageStatus = "embedding_storage_status"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encode(tags, forKey: .tags)
        try codingContainer.encode(id, forKey: .id)
        try codingContainer.encode(source, forKey: .source)
        try codingContainer.encode(organizationId, forKey: .organizationId)
        try codingContainer.encode(organizationSuppliedUserId, forKey: .organizationSuppliedUserId)
        try codingContainer.encode(organizationUserDataSourceId, forKey: .organizationUserDataSourceId)
        try codingContainer.encode(externalFileId, forKey: .externalFileId)
        try codingContainer.encode(externalUrl, forKey: .externalUrl)
        try codingContainer.encode(syncStatus, forKey: .syncStatus)
        try codingContainer.encode(syncErrorMessage, forKey: .syncErrorMessage)
        try codingContainer.encode(lastSync, forKey: .lastSync)
        try codingContainer.encode(fileStatistics, forKey: .fileStatistics)
        try codingContainer.encode(fileMetadata, forKey: .fileMetadata)
        try codingContainer.encode(embeddingProperties, forKey: .embeddingProperties)
        try codingContainer.encode(chunkSize, forKey: .chunkSize)
        try codingContainer.encode(chunkOverlap, forKey: .chunkOverlap)
        try codingContainer.encode(chunkProperties, forKey: .chunkProperties)
        try codingContainer.encode(ocrProperties, forKey: .ocrProperties)
        try codingContainer.encode(ocrJobStartedAt, forKey: .ocrJobStartedAt)
        try codingContainer.encode(name, forKey: .name)
        try codingContainer.encode(parentId, forKey: .parentId)
        try codingContainer.encode(enableAutoSync, forKey: .enableAutoSync)
        try codingContainer.encode(presignedUrl, forKey: .presignedUrl)
        try codingContainer.encode(parsedTextUrl, forKey: .parsedTextUrl)
        try codingContainer.encode(additionalPresignedUrls, forKey: .additionalPresignedUrls)
        try codingContainer.encode(skipEmbeddingGeneration, forKey: .skipEmbeddingGeneration)
        try codingContainer.encode(sourceCreatedAt, forKey: .sourceCreatedAt)
        try codingContainer.encode(generateSparseVectors, forKey: .generateSparseVectors)
        try codingContainer.encode(requestId, forKey: .requestId)
        try codingContainer.encode(uploadId, forKey: .uploadId)
        try codingContainer.encode(syncProperties, forKey: .syncProperties)
        try codingContainer.encode(messagesMetadata, forKey: .messagesMetadata)
        try codingContainer.encode(fileContentsDeleted, forKey: .fileContentsDeleted)
        try codingContainer.encode(supportsColdStorage, forKey: .supportsColdStorage)
        try codingContainer.encode(hotStorageTimeToLive, forKey: .hotStorageTimeToLive)
        try codingContainer.encode(embeddingStorageStatus, forKey: .embeddingStorageStatus)
        try codingContainer.encode(createdAt, forKey: .createdAt)
        try codingContainer.encode(updatedAt, forKey: .updatedAt)
    }
}

