//
// WhiteLabelOrderByColumns.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum WhiteLabelOrderByColumns: String, Codable, CaseIterable {
    case createdAt = "created_at"
    case dataSourceType = "data_source_type"
}
