//
// WhiteLabelingResponse.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WhiteLabelingResponse: Codable, JSONEncodable, Hashable {

    public var removeBranding: Bool
    public var integrations: AnyCodable
    public var customLimits: AnyCodable
    public var connectorSettings: AnyCodable

    public init(removeBranding: Bool, integrations: AnyCodable, customLimits: AnyCodable, connectorSettings: AnyCodable) {
        self.removeBranding = removeBranding
        self.integrations = integrations
        self.customLimits = customLimits
        self.connectorSettings = connectorSettings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case removeBranding = "remove_branding"
        case integrations
        case customLimits = "custom_limits"
        case connectorSettings = "connector_settings"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encode(removeBranding, forKey: .removeBranding)
        try codingContainer.encode(integrations, forKey: .integrations)
        try codingContainer.encode(customLimits, forKey: .customLimits)
        try codingContainer.encode(connectorSettings, forKey: .connectorSettings)
    }
}

