//
// WhiteLabelFilters.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WhiteLabelFilters: Codable, JSONEncodable, Hashable {

    public var ids: [Int]?
    public var dataSourceType: [OauthBasedConnectors]?

    public init(ids: [Int]? = nil, dataSourceType: [OauthBasedConnectors]? = nil) {
        self.ids = ids
        self.dataSourceType = dataSourceType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ids
        case dataSourceType = "data_source_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encodeIfPresent(ids, forKey: .ids)
        try codingContainer.encodeIfPresent(dataSourceType, forKey: .dataSourceType)
    }
}

