//
// ZendeskFileTypes.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ZendeskFileTypes: String, Codable, CaseIterable {
    case ticket = "TICKET"
    case article = "ARTICLE"
    case ticketAttachment = "TICKET_ATTACHMENT"
    case section = "SECTION"
    case category = "CATEGORY"
}
